### ISSUE TITLE
Refactor struct Query

### ISSUE THREAD

**Issue by miporto** [abrden/database#6]
The Query should support both messages to the Server and to the Client. So it should be named Message (and modified accordingly) as it is more appropriate.

It should also be refactored as it's shown in the attached image.
![image](https://user-images.githubusercontent.com/7240098/41514807-329d51a2-7280-11e8-89b5-b118c2265cbc.jpg)

**Comment by aibarbetta** [comment]
- [x] memsets on every serialize
- [x] make serialize methods constant
- [x] separate Query from Entry
- [x] Move QueryData to Query.h
